// Carga inicial do menu do salão: extraído do menu-salao.html da Versão 3
// (Desktop\Nikolas\Cardápio\Salão\Versão 3), que era a fonte da peça impressa.
// Gerado por scripts/gera-seed-salao.mjs — não editar à mão; a edição de verdade
// acontece no painel, e o que vale passa a ser o arquivo no Blob.

import type { MenuSalao } from "./tipos";

export const SALAO_INICIAL: MenuSalao = {
  frase: "A mesa do Sr. Nicola, desde 1977.",
  historia: [
    "O Nikola's começou no fim dos anos 70, numa antiga casa da Rua Floriano Peixoto, com uma cozinha de quinze metros quadrados e mesas emprestadas.",
    "Quem abriu a porta foram Nicola Tahan, comerciante paulista de origem sírio-libanesa, e Zenaide, sua mulher, mineira. Os dois sabiam receber: a casa vivia cheia, com a família e os amigos em volta de uma mesa farta. Foi essa mesa que eles trouxeram para o negócio.",
    "Da cozinha do Sr. Nicola saíram os pratos que estão neste menu até hoje: as carnes no corte certo, o kibe chapado, a salada de maionese, o feijão tropeiro.",
    "Alguns anos depois, a lanchonete cresceu, mudou para este endereço e virou restaurante. O Sr. Nicola fazia questão de receber e conhecer cada cliente, mandava para a mesa a degustação do dia e soltava uma piada. Todos sorriam.",
    "Quase cinquenta anos depois, o Nikola's continua sendo o lugar para chegar e comer, sentar e ficar. Reunir a família, encontrar os amigos, pedir o prato de sempre ou provar um novo — e reencontrar, a cada visita, as raízes de Ouro Fino.",
  ],
  folhas: [
    { titulo: "Nossa história", variantes: ["historia", "semnumero"], miolo: "hist", quadro: false, grupos: [], quadroSecoes: [], secoes: [] },
    { titulo: "Para começar", variantes: [], miolo: "lq", quadro: true, fecho: "A mesa do Sr. Nicola, desde 1977.", grupos: [["entradas", "frios"]], quadroSecoes: ["arabes"], secoes: ["entradas", "frios", "arabes"] },
    { titulo: "Petiscos", variantes: ["justa"], miolo: "duas-col", quadro: false, grupos: [["quentes"], ["chapa"]], quadroSecoes: [], secoes: ["quentes", "chapa"] },
    { titulo: "Carnes", variantes: [], miolo: "", quadro: false, grupos: [["carnes"]], quadroSecoes: [], secoes: ["carnes"] },
    { titulo: "Aves, peixes e especiais", variantes: [], miolo: "", quadro: false, fecho: "Feijão tropeiro, todos os dias.", grupos: [["aves"], ["peixes"]], quadroSecoes: ["especiais"], secoes: ["aves", "peixes", "especiais"] },
    { titulo: "Massas, sanduíches e porções", variantes: [], miolo: "duas-col", quadro: false, grupos: [["massas"], ["adicionais", "sanduiches"]], quadroSecoes: [], secoes: ["massas", "adicionais", "sanduiches"] },
    { titulo: "Drinks, sucos e refrigerantes", variantes: [], miolo: "duas-col", quadro: false, grupos: [["drinks"], ["sucos", "refrigerantes"]], quadroSecoes: [], secoes: ["drinks", "sucos", "refrigerantes"] },
    { titulo: "Chope, cachaças e doses", variantes: [], miolo: "duas-col", quadro: false, grupos: [["cervejas", "cachacas"], ["doses"]], quadroSecoes: [], secoes: ["cervejas", "cachacas", "doses"] },
    { titulo: "Especiais\nde domingo", variantes: ["domingo", "semnumero"], miolo: "", quadro: false, abre: true, eyebrow: "Só no almoço de domingo", frase: "Pratos que só saem da cozinha uma vez por semana.", rodapeN: "Domingo", grupos: [["domingo"]], quadroSecoes: [], secoes: ["domingo"] },
  ],
  secoes: [
    {
      id: "entradas",
      titulo: "Entradas",
      colunas: ["1 pessoa", "2 pessoas"],
      itens: [
      { nome: "Salada simples", desc: "Alface, tomate e cebola.", precos: [18] },
      { nome: "Salada mista", desc: "Legumes cozidos, palmito, alface, tomate e cebola.", precos: [23, 38] },
      { nome: "Salada de palmito", desc: "Palmito em rodelas, com azeite.", precos: [35] },
      { nome: "Maionese", desc: "A salada de maionese do Sr. Nicola, com batata e legumes.", precos: [20] },
      { nome: "Berinjela", desc: "Berinjela em cubos com tomate, cebola e especiarias, ao azeite.", precos: [18] },
      { nome: "Salada verde", desc: "Folhas verdes, tomate seco e palmito.", precos: [40] },
      ],
    },
    {
      id: "frios",
      titulo: "Petiscos frios",
      itens: [
      { nome: "Salame", desc: "Em fatias finas.", precos: [24] },
      { nome: "Copa", desc: "Em fatias finas.", precos: [24] },
      { nome: "Tábua de frios", desc: "Provolone, gorgonzola, salame, copa e azeitonas.", precos: [78] },
      { nome: "Queijo provolone", desc: "Em cubos.", precos: [24] },
      { nome: "Queijo gorgonzola", desc: "Em cubos.", precos: [26] },
      { nome: "Queijo parmesão", desc: "Em lascas.", precos: [26] },
      { nome: "Azeitonas", desc: "Pretas ou verdes, à escolha.", precos: [15] },
      ],
    },
    {
      id: "arabes",
      titulo: "Especialidades árabes",
      itens: [
      { nome: "Filé mignon à moda árabe", desc: "Tiras de filé mignon com homus e amêndoas laminadas.", precos: [89] },
      { nome: "Kibe cru", desc: "Carne moída com trigo, cebola e hortelã, servida crua, com azeite.", dia: "Quinta a sábado", precos: [25] },
      { nome: "Kibe chapado com queijo", desc: "Kibe aberto na chapa, coberto com queijo.", dia: "Quinta a sábado", precos: [23] },
      { nome: "Kafta", desc: "Carne moída com especiarias árabes, na chapa.", unidade: "4 unidades", dia: "Quinta a sábado", precos: [28] },
      { nome: "Kafta com tabule", desc: "A kafta com salada de trigo, tomate, salsa e hortelã.", unidade: "4 unidades", dia: "Quinta a sábado", precos: [39] },
      { nome: "Tábua Dona Zena", desc: "Kibe cru, homus, babaganuche e pão sírio.", dia: "Quinta a sábado", precos: [52] },
      { nome: "Tábua Dona Zena completa", desc: "Kibe cru, homus, babaganuche, tabule, kafta e pão sírio.", dia: "Quinta a sábado", precos: [88] },
      { nome: "Homus", desc: "Pasta de grão-de-bico com tahine, limão e azeite.", dia: "Quinta a sábado", precos: [14] },
      { nome: "Babaganuche", desc: "Pasta de berinjela assada com tahine e azeite.", dia: "Quinta a sábado", precos: [14] },
      ],
    },
    {
      id: "quentes",
      titulo: "Quentes",
      itens: [
      { nome: "Bolinho de linguiça recheado", desc: "Massa de linguiça com recheio cremoso, frito na hora.", unidade: "4 unidades", precos: [42] },
      { nome: "Bolinho de bacalhau especial", desc: "Bacalhau desfiado com batata, frito na hora.", unidade: "4 unidades", precos: [44] },
      { nome: "Bolinho de feijoada recheado", desc: "Massa de feijoada com recheio, frito na hora.", unidade: "4 unidades", precos: [36] },
      { nome: "Croquete de carne", desc: "Carne moída temperada, empanada e frita.", unidade: "15 unidades", precos: [33] },
      { nome: "Bolinho de queijo", desc: "Massa leve com recheio de queijo, frito na hora.", unidade: "15 unidades", precos: [25] },
      { nome: "Mix bolinhos de boteco", desc: "Seleção dos bolinhos da casa.", unidade: "22 unidades", precos: [80] },
      { nome: "Fritas", desc: "Porção de batata frita.", precos: [25] },
      { nome: "Fritas com queijo e bacon", desc: "Batata frita coberta com queijo derretido e bacon.", precos: [34] },
      { nome: "Torresmo", desc: "Torresmo mineiro, crocante.", precos: [16] },
      { nome: "Polenta frita", desc: "Polenta em palitos, frita.", precos: [28] },
      { nome: "Trem mineiro", desc: "Batata noisette, linguiça, torresmo e polenta frita, com molho barbecue.", precos: [69] },
      { nome: "Língua ao molho de vinho com farofa", desc: "Língua bovina cozida ao molho de vinho tinto, com farofa.", precos: [30] },
      { nome: "Frango à passarinho com molho barbecue", desc: "Pedaços de frango fritos com alho, com molho barbecue.", precos: [38] },
      { nome: "Isca de frango com molho tártaro", desc: "Tiras de frango empanadas, com molho tártaro.", precos: [38] },
      { nome: "Isca de peixe com molho tártaro", desc: "Tiras de peixe empanadas, com molho tártaro.", precos: [62] },
      { nome: "Mix dos mares", desc: "Camarão empanado, iscas de peixe, lula à dorê e bolinho de bacalhau, com molho tártaro.", precos: [90] },
      { nome: "Provolone à milanesa", desc: "Fatias de provolone empanadas e fritas.", precos: [35] },
      ],
    },
    {
      id: "chapa",
      titulo: "Na chapa",
      itens: [
      { nome: "Picanha ao palito com torradas ao creme de alho", desc: "Cubos de picanha na chapa, com torradas e creme de alho.", unidade: "500 g", precos: [98] },
      { nome: "Picanha ao palito acebolado", desc: "Cubos de picanha na chapa, com cebola.", unidade: "500 g", precos: [89] },
      { nome: "Filé ao palito com torradas ao creme de alho", desc: "Cubos de filé mignon na chapa, com torradas e creme de alho.", unidade: "500 g", precos: [96] },
      { nome: "Filé ao palito acebolado", desc: "Cubos de filé mignon na chapa, com cebola.", unidade: "500 g", precos: [89] },
      { nome: "Contra filé ao palito acebolado", desc: "Cubos de contra filé na chapa, com cebola.", unidade: "500 g", precos: [68] },
      { nome: "Tiras de lombo acebolado gratinado com provolone", desc: "Lombo em tiras com cebola, gratinado com provolone.", precos: [71] },
      { nome: "Lombo ao palito acebolado", desc: "Cubos de lombo na chapa, com cebola.", unidade: "500 g", precos: [57] },
      { nome: "Frango ao catupiry acebolado e gratinado", desc: "Frango na chapa com cebola, coberto com catupiry gratinado.", precos: [58] },
      { nome: "Frango ao palito acebolado", desc: "Cubos de frango na chapa, com cebola.", precos: [39] },
      { nome: "Linguiça de rolo artesanal recheada com queijo", desc: "Na chapa. Acompanha polenta frita.", precos: [75] },
      { nome: "Trio especial", desc: "Linguiça de rolo recheada de queijo, mini medalhões de frango e polenta frita, com molho barbecue.", precos: [98] },
      ],
    },
    {
      id: "sanduiches",
      titulo: "Sanduíches Nikola's",
      itens: [
      { nome: "Lombo", desc: "Lombo grelhado no pão francês, com cebola, muçarela, tomate e molho shoyu. Acompanha fritas.", precos: [28] },
      { nome: "Filé mignon", desc: "Filé mignon grelhado no pão francês, com cebola, muçarela, tomate e molho shoyu. Acompanha fritas.", precos: [32] },
      { nome: "Frango", desc: "Filé de frango grelhado no pão francês, com cebola, muçarela, tomate e molho shoyu. Acompanha fritas.", precos: [25] },
      ],
    },
    {
      id: "carnes",
      colunas: ["1 pessoa", "2 pessoas"],
      itens: [
      { nome: "Picanha maturada no espeto", desc: "Picanha Estância 92, maturada, assada no espeto. Acompanha arroz, feijão tropeiro e fritas.", precos: [126, 196] },
      { nome: "Picanha maturada fatiada", desc: "Picanha Estância 92, maturada, em fatias. Acompanha arroz, feijão tropeiro e fritas.", precos: [126, 196] },
      { nome: "Picanha simples", desc: "Grelhada, sem acompanhamentos: 280 g para uma pessoa, 500 g para duas.", precos: [90, 140] },
      { nome: "Filé mignon 4 queijos ao molho branco", desc: "Medalhões de filé mignon ao molho branco de quatro queijos. Acompanha arroz e fritas.", precos: [110, 174] },
      { nome: "Filé mignon", desc: "Grelhado. Acompanha arroz, feijão tropeiro e fritas.", precos: [110, 174] },
      { nome: "Filé mignon simples", desc: "Grelhado, sem acompanhamentos: 280 g para uma pessoa, 500 g para duas.", precos: [79, 112] },
      { nome: "Filé mignon à parmegiana", desc: "Empanado, com molho de tomate e queijo gratinado. Acompanha arroz e fritas.", precos: [110, 174] },
      { nome: "Lombo da casa", desc: "Lombo suíno preparado do jeito da casa. Acompanha arroz, feijão tropeiro e fritas.", precos: [85, 128] },
      { nome: "Lombo grelhado", desc: "Lombo suíno grelhado. Acompanha arroz, feijão tropeiro e fritas.", precos: [85, 128] },
      { nome: "Lombo simples", desc: "Grelhado, sem acompanhamentos: 280 g para uma pessoa, 500 g para duas.", precos: [48, 71] },
      { nome: "Espeto misto", desc: "Contra filé, frango e lombo no espeto. Acompanha arroz, feijão tropeiro e fritas.", precos: [110, 168] },
      { nome: "Espeto misto Nikola's", desc: "Picanha, frango e lombo no espeto. Acompanha arroz, feijão tropeiro e fritas.", precos: [128, 189] },
      { nome: "Espeto nobre", desc: "Picanha e filé mignon no espeto. Acompanha arroz, feijão tropeiro e fritas.", precos: [130, 198] },
      { nome: "Contra filé maturado", desc: "Grelhado. Acompanha arroz, feijão tropeiro e fritas.", precos: [82, 134] },
      { nome: "Contra filé simples", desc: "Grelhado, sem acompanhamentos: 280 g para uma pessoa, 500 g para duas.", precos: [51, 82] },
      ],
    },
    {
      id: "aves",
      titulo: "Aves",
      colunas: ["1 pessoa", "2 pessoas"],
      itens: [
      { nome: "Frango simples", desc: "Filé de frango grelhado, sem acompanhamentos.", precos: [29, 50] },
      { nome: "Filé de frango grelhado", desc: "Acompanha arroz, feijão tropeiro e fritas.", precos: [58, 88] },
      { nome: "Filé de frango à parmegiana", desc: "Empanado, com molho de tomate e queijo gratinado. Acompanha arroz e fritas.", precos: [58, 88] },
      { nome: "Filé de frango ao molho branco e catupiry", desc: "Grelhado, coberto com molho branco e catupiry. Acompanha arroz e fritas.", precos: [58, 88] },
      { nome: "Filé de frango à milanesa", desc: "Empanado e frito. Acompanha arroz, feijão tropeiro e fritas.", precos: [58, 88] },
      ],
    },
    {
      id: "peixes",
      titulo: "Peixes",
      colunas: ["1 pessoa", "2 pessoas"],
      itens: [
      { nome: "Filé de peixe simples", desc: "Grelhado, sem acompanhamentos.", precos: [52, 78] },
      { nome: "Filé de peixe à milanesa", desc: "Empanado e frito. Acompanha arroz, legumes e fritas.", precos: [74, 116] },
      { nome: "Filé de peixe à parmegiana", desc: "Empanado, com molho de tomate e queijo gratinado. Acompanha arroz e fritas.", precos: [74, 116] },
      { nome: "Salmão simples", desc: "Grelhado, sem acompanhamentos.", precos: [76, 118] },
      { nome: "Salmão à Nikola's", desc: "Grelhado, do jeito da casa. Acompanha arroz, legumes e fritas.", precos: [101, 164] },
      ],
    },
    {
      id: "especiais",
      titulo: "Especiais",
      colunas: ["1 pessoa", "2 pessoas"],
      itens: [
      { nome: "Dobradinha à moda", desc: "Dobradinha cozida lentamente, à moda da casa.", dia: "Quarta-feira", precos: [48, 75] },
      { nome: "Viradão à mineira", desc: "Bisteca de porco, lombo e calabresa com tutu de feijão, couve, torresmo, banana à milanesa e abacaxi. Acompanha arroz e fritas.", dia: "Quinta a domingo", precos: [98, 148] },
      { nome: "Viradão com filé", desc: "O viradão à mineira servido com filé mignon.", dia: "Quinta a domingo", precos: [128, 189] },
      { nome: "Viradão com contra filé", desc: "O viradão à mineira servido com contra filé.", dia: "Quinta a domingo", precos: [99, 154] },
      { nome: "Viradão com picanha", desc: "O viradão à mineira servido com picanha.", dia: "Quinta a domingo", precos: [138, 215] },
      ],
    },
    {
      id: "adicionais",
      titulo: "Porções adicionais",
      colunas: ["Meia", "Inteira"],
      itens: [
      { nome: "Feijão tropeiro", desc: "Feijão com farinha de mandioca, linguiça, torresmo, ovo e couve.", precos: [14, 22] },
      { nome: "Arroz branco", desc: "Porção de arroz branco.", precos: [8, 12] },
      { nome: "Fritas", desc: "Porção de batata frita.", precos: [28] },
      { nome: "Torresmo", desc: "Porção de torresmo crocante.", precos: [16] },
      { nome: "Ovo frito", desc: "Uma unidade.", precos: [3] },
      { nome: "Omelete da casa", desc: "Queijo, cebola, ervilha e tomate.", precos: [23] },
      { nome: "Omelete simples com queijo", desc: "Omelete com queijo.", precos: [16] },
      { nome: "Alho e óleo", desc: "Alho dourado no óleo, para temperar.", precos: [4] },
      { nome: "Banana à milanesa", desc: "Banana empanada e frita.", precos: [6] },
      ],
    },
    {
      id: "massas",
      titulo: "Massas caseiras Nikola's",
      nota: "Molho ao sugo, branco ou rosê.",
      itens: [
      { nome: "Lasanha à bolonhesa", desc: "Camadas de massa com molho de carne e queijo.", precos: [44] },
      { nome: "Lasanha presunto e queijo", desc: "Camadas de massa com presunto e queijo.", precos: [44] },
      { nome: "Lasanha 4 queijos", desc: "Camadas de massa com quatro queijos.", precos: [44] },
      { nome: "Rondeli de frango", desc: "Massa enrolada com recheio de frango.", precos: [44] },
      { nome: "Rondeli de ricota e espinafre", desc: "Massa enrolada com recheio de ricota e espinafre.", precos: [45] },
      { nome: "Ravioli de carne", desc: "Massa recheada de carne.", precos: [49] },
      { nome: "Ravioli de queijo", desc: "Massa recheada de queijo.", precos: [49] },
      { nome: "Ravioli de massa verde com alho-poró e muçarela de búfala", desc: "Massa de espinafre recheada de alho-poró e muçarela de búfala.", precos: [65] },
      { nome: "Capeletti de carne", desc: "Pequenas trouxinhas de massa recheadas de carne.", precos: [49] },
      { nome: "Nhoque recheado de queijo", desc: "Nhoque de batata com recheio de queijo.", precos: [42] },
      { nome: "Manicaretti à caprese", desc: "Massa recheada de muçarela de búfala, tomate seco e manjericão.", precos: [62] },
      { nome: "Talharim", desc: "Massa fresca em tiras, com o molho à escolha.", precos: [28] },
      ],
    },
    {
      id: "sucos",
      titulo: "Sucos",
      itens: [
      { nome: "Laranja natural", desc: "Espremida na hora.", precos: [12] },
      { nome: "Acerola", desc: "Batido na hora.", precos: [10] },
      { nome: "Abacaxi", desc: "Batido na hora.", precos: [10] },
      { nome: "Abacaxi com hortelã", desc: "Abacaxi batido na hora com folhas de hortelã.", precos: [10] },
      { nome: "Caju", desc: "Batido na hora.", precos: [10] },
      { nome: "Limão", desc: "Batido na hora.", precos: [10] },
      { nome: "Maracujá", desc: "Batido na hora.", precos: [10] },
      { nome: "Amora", desc: "Batido na hora.", precos: [12] },
      { nome: "Del Valle uva", desc: "Lata 290 ml.", precos: [12] },
      ],
    },
    {
      id: "refrigerantes",
      titulo: "Refrigerantes e águas",
      itens: [
      { nome: "Refrigerante lata", desc: "Lata 350 ml.", precos: [8] },
      { nome: "Refrigerante 600 ml", desc: "Garrafa 600 ml.", precos: [12] },
      { nome: "Refrigerante KS", desc: "Garrafa de vidro 290 ml.", precos: [7] },
      { nome: "H2OH", desc: "Garrafa 500 ml.", precos: [7] },
      { nome: "Água Prata", desc: "Com ou sem gás.", precos: [7] },
      { nome: "Água mineral Nestlé ou Crystal", desc: "Sem gás.", precos: [6] },
      ],
    },
    {
      id: "drinks",
      titulo: "Drinks",
      itens: [
      { nome: "Caipirinha de cachaça", desc: "Cachaça, limão, açúcar e gelo.", precos: [22] },
      { nome: "Caipiroska Smirnoff", desc: "Vodka Smirnoff com limão, abacaxi, kiwi ou morango.", precos: [28] },
      { nome: "Caipiroska de amora com espuma de morango", desc: "Vodka e amora, com espuma de morango por cima.", precos: [32] },
      { nome: "Saquerinha", desc: "Saquê com limão, abacaxi ou kiwi.", precos: [25] },
      { nome: "Caipiroska Absolut", desc: "Vodka Absolut com limão, abacaxi, kiwi ou morango.", precos: [34] },
      { nome: "Piña colada", desc: "Vodka, leite condensado, leite de coco e abacaxi, batidos com gelo.", precos: [30] },
      { nome: "Mojito com espuma de gengibre", desc: "Rum, limão, hortelã e soda, com espuma de gengibre.", precos: [28] },
      { nome: "Gin tônica com espuma de limão", desc: "Gin, água tônica e espuma de limão.", precos: [28] },
      { nome: "Gin tônica com limão siciliano", desc: "Gin, água tônica e limão siciliano.", precos: [28] },
      { nome: "Drink de frutas", desc: "Vodka ou saquê batido com morango, kiwi ou abacaxi.", precos: [28] },
      { nome: "Marguerita", desc: "Tequila, Cointreau e limão.", precos: [35] },
      { nome: "Red Bull", desc: "Energético, lata 250 ml.", precos: [17] },
      { nome: "Aperol Spritz", desc: "Aperol, espumante e laranja.", precos: [35] },
      ],
    },
    {
      id: "cachacas",
      titulo: "Cachaças",
      itens: [
      { nome: "Salinas", desc: "De Salinas, Minas Gerais. Dose.", precos: [7] },
      { nome: "Boazinha Salinas", desc: "De Salinas, Minas Gerais. Dose.", precos: [7] },
      { nome: "Minas de Ouro", desc: "Cachaça da terra. Dose.", precos: [7] },
      { nome: "Bonito", desc: "Cachaça da terra. Dose.", precos: [7] },
      { nome: "Do Antenor", desc: "Cachaça da terra. Dose.", precos: [7] },
      ],
    },
    {
      id: "cervejas",
      titulo: "Chope e cervejas",
      itens: [
      { nome: "Chope Brahma claro", desc: "Tirado na hora.", unidade: "500 ml", precos: [17] },
      { nome: "Chope Brahma claro", desc: "Tirado na hora.", unidade: "350 ml", precos: [12] },
      { nome: "Chope Brahma claro garotinho", desc: "Tirado na hora.", unidade: "210 ml", precos: [10] },
      { nome: "Chope Brahma black", desc: "Chope escuro, tirado na hora.", unidade: "430 ml", precos: [16] },
      { nome: "Original", desc: "Garrafa.", unidade: "600 ml", precos: [17] },
      { nome: "Serramalte", desc: "Garrafa.", unidade: "600 ml", precos: [17] },
      { nome: "Skol", desc: "Garrafa.", unidade: "600 ml", precos: [14] },
      { nome: "Brahma", desc: "Garrafa.", unidade: "600 ml", precos: [14] },
      { nome: "Heineken", desc: "Garrafa.", unidade: "600 ml", precos: [18] },
      { nome: "Heineken", desc: "Garrafa 330 ml.", unidade: "long neck", precos: [12] },
      ],
    },
    {
      id: "doses",
      titulo: "Doses",
      itens: [
      { nome: "Vodka Absolut", desc: "Vodka sueca. Dose.", precos: [20] },
      { nome: "Vodka Smirnoff", desc: "Dose.", precos: [15] },
      { nome: "Gin Tanqueray", desc: "Gin inglês. Dose.", precos: [20] },
      { nome: "Rum", desc: "Dose.", precos: [13] },
      { nome: "Martini", desc: "Vermute. Dose.", precos: [13] },
      { nome: "Campari", desc: "Bitter italiano. Dose.", precos: [15] },
      { nome: "Underberg", desc: "Digestivo alemão de ervas, garrafinha 20 ml.", precos: [10] },
      { nome: "Cointreau", desc: "Licor de laranja. Dose.", precos: [18] },
      { nome: "Conhaque Domecq", desc: "Dose.", precos: [10] },
      { nome: "Whisky Jack Daniel's", desc: "Whisky americano. Dose.", precos: [27] },
      { nome: "Whisky Red Label", desc: "Whisky escocês. Dose.", precos: [27] },
      { nome: "Whisky Black Label", desc: "Whisky escocês 12 anos. Dose.", precos: [32] },
      { nome: "Steinhaeger", desc: "Destilado de zimbro. Dose.", precos: [10] },
      ],
    },
    {
      id: "domingo",
      nota: "Servidos enquanto durarem.",
      colunas: ["1 pessoa", "2 pessoas"],
      itens: [
      { nome: "Leitoa à pururuca", desc: "Com arroz, tutu de feijão, couve refogada e farofa.", precos: [98, 148] },
      { nome: "Costela no bafo", desc: "Assada por horas, com mandioca cozida e vinagrete.", precos: [110, 168] },
      { nome: "Galinhada caipira", desc: "Arroz com frango caipira, açafrão e cheiro-verde.", precos: [79, 120] },
      { nome: "Feijoada completa", desc: "Com arroz, couve, farofa, torresmo e laranja.", precos: [89, 138] },
      ],
    },
  ],
};
